name: Go
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.11
        uses: actions/setup-go@v2
        with:
          go-version: 1.11
        id: go

      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          go test -v ./tests/...
